"""empty message

Revision ID: 4ff22756e864
Revises: 665e798d8f2b
Create Date: 2025-01-08 00:13:21.507352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff22756e864'
down_revision = '665e798d8f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_Name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_Name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_Name')
        batch_op.drop_column('first_Name')

    # ### end Alembic commands ###
